{{- if .Values.monitoring.enabled }}
{{- range $name,$value := .Values.agents }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eggai-multi-agent-chat.fullname" $ }}-{{ lower $name }}-metrics
  labels:
    {{- include "eggai-multi-agent-chat.labels" $ | nindent 4 }}
    app.kubernetes.io/component: monitoring
    egg-ai.com/agent: {{ $name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $.Values.monitoring.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "eggai-multi-agent-chat.selectorLabels" $ | nindent 4 }}
    egg-ai.com/agent: {{ $name }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "eggai-multi-agent-chat.fullname" $ }}-{{ lower $name }}
  labels:
    {{- include "eggai-multi-agent-chat.labels" $ | nindent 4 }}
spec:
  endpoints:
  - honorLabels: true
    interval: {{ $.Values.monitoring.serviceMonitor.interval | default "30s" }}
    path: /metrics
    port: metrics
    scheme: http
    scrapeTimeout: {{ $.Values.monitoring.serviceMonitor.scrapeTimeout | default "10s" }}
  selector:
    matchLabels:
      {{- include "eggai-multi-agent-chat.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: monitoring
      egg-ai.com/agent: {{ $name }}
{{- end }}
{{- end }}
